accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
  path('signup/', views.signup, name='signup'),
  path('<str:username>/profile/', views.profile, name='profile'),
  path('bioupdate/<str:username>/', views.bio, name='bio'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),     
    path('accounts/', include('accounts.urls')),
    path('', include('follows.urls')),
]

likes/urls.py
from django.urls import path

urlpatterns = [
  path('like/<int:user_id>/', like)
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    # path('individualpost/<str:username>/', views.individual, name='individual'),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.delete, name='delete'),
]

posts/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Tweet(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=140)
    # image = models.ImageField(upload_to='tweets/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

posts/views.py
from django.shortcuts import redirect, render

from likes.models import Like
from .models import Tweet
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.core.exceptions import PermissionDenied

User = get_user_model()

class IndexView(View):
  def get(self, request):
    data_list = Tweet.objects.all().order_by('-created_at')
    
    for tweet in data_list:
      tweet.like_count = Like.objects.filter(tweet=tweet).count()

  
    return render(request, 'posts/index.html', {'data_list':data_list})
  
  def post(self, request):
    tweet_id = request.POST.get('tweet_id')
    tweet = get_object_or_404(Tweet, id=tweet_id)
    user = request.user
    
    like, created = Like.objects.get_or_create(user=user, tweet=tweet)

    if created:
      like.like_count += 1
      like.save()

    return redirect('posts:index')


index = IndexView.as_view()


class CreateView(LoginRequiredMixin, generic.edit.CreateView):
  model = Tweet
  fields = ['content']
  template_name = 'posts/create.html'
  success_url = '/'

  def form_valid(self, form):
    form.instance.author = self.request.user
    return super().form_valid(form)
  
create = CreateView.as_view()


class UpdateView(LoginRequiredMixin, generic.edit.UpdateView):
  model = Tweet
  fields = ['content']
  template_name = 'posts/update.html'
  success_url = '/'
  
  def dispatch(self, request, *args, **kwargs):
    obj = self.get_object()
    if obj.author != self.request.user:
      raise PermissionDenied('編集権限がありません')
    return super().dispatch(request, *args, **kwargs)
  
update = UpdateView.as_view()


class DeleteView(LoginRequiredMixin, generic.edit.DeleteView):
  model = Tweet
  template_name = 'posts/delete.html'
  success_url = '/'
  
  def dispatch(self, request, *args, **kwargs):
      obj = self.get_object()
      if obj.author != self.request.user:
          raise PermissionDenied('削除権限がありません。')
      return super().dispatch(request, *args, **kwargs)
    
delete = DeleteView.as_view()

templates/posts/create.html
{% extends 'base.html' %}

{% block content %}

<div class="create">
  <h1>ツイート</h1>
  <form action="" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>投稿</button>
  </form>
</div>

{% endblock %}

templates/posts/delete.html
{% extends 'base.html' %}

{% block content  %}

<div class="delete">
  <h1>削除</h1>
  <form action="" method='post'>
    {% csrf_token %}
    <button type='submit'>削除</button>
  </form>
</div>
{% endblock content  %}

templates/posts/index.html
{% extends 'base.html' %}

{% block content %}

<div class="index">
  {% for data in data_list %}
  <div class="postCard">
    <div><a class='userName' href="{% url 'accounts:profile' data.author.username %}">{{ data.author.username }}</a> :{{ data.created_at }}</div>

    <div class='body'>{{ data.content }}</div>
    
    <div class="buttons">
      <a class='update' href="{% url 'posts:update' data.pk %}">編集</a>
      <a class='delete' href="{% url 'posts:delete' data.id %}">削除</a>
    </div>
    
    <form action="" method='post'>
      {% csrf_token %}
      <input type="hidden" name="tweet_id" value="{{ data.id }}">
      <p><button type='submit'>いいね</button>:{{ data.like_count }}</p>
    </form>
    
  </div>
  {% endfor %}
  
  {% comment %} <a href="{% url 'posts:create' %}">新規投稿</a> {% endcomment %}
  <a href="{% url 'posts:create' %}" class='postBtn'>＋</a>

</div>

{% endblock %}

templates/posts/update.html
{% extends 'base.html' %}

{% block content %}

<div class="update">
  <h1>{{ object.id }}</h1>
  <form action="" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>更新</button>
  </form>
</div>

{% endblock content %}