accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
  path('signup/', views.signup, name='signup'),
  path('<str:username>/profile/', views.profile, name='profile'),
  path('bioupdate/<str:username>/', views.bio, name='bio'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),     
    path('accounts/', include('accounts.urls')),
    path('', include('follows.urls')),
]

likes/urls.py
from django.urls import path

urlpatterns = [
  path('like/<int:user_id>/', like)
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    # path('individualpost/<str:username>/', views.individual, name='individual'),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.delete, name='delete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://unpkg.com/modern-css-reset/dist/reset.min.css">   {# リセットCSS #}
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
  <title>Document</title>
</head>
<body>
  <div class="header">
    <a class="jobX" href="{% url 'posts:index' %}">JobiX</a>
    <nav>
      <div class="btn">
        <i></i>
        <i></i>
        <i></i>
      </div>
  </div>
  
    <div class="container">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
      <div class="item">
        <ul>
          {% if user.is_authenticated %}
            <h2>{{ user }}でログイン中</h2>
          {% else %}
            <li><a href="{% url 'login' %}">ログイン</a></li>
          {% endif %}
          
          <li><a href="{% url 'logout' %}">ログアウト</a></li>
          <li><a href="{% url 'accounts:signup' %}">新規作成</a></li>
          {% comment %} <li><a href="{% url 'accounts:profile' data.author.username %}">プロフィールへ</a></li> {% endcomment %}
        </ul>
      </div>
    </div>
  </nav>

  <button id="upBottom">↑</button>
  <button id="scrollToBottom">↓</button>

  <div class="main">

    {% block content %}
    {% endblock %}
    
  </div>
  <script src="{% static 'js/index.js' %}"></script>
</body>
</html>