accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
  path('signup/', views.signup, name='signup'),
  path('<str:username>/profile/', views.profile, name='profile'),
  path('bioupdate/<str:username>/', views.bio, name='bio'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),     
    path('accounts/', include('accounts.urls')),
    path('', include('follows.urls')),
]

likes/urls.py
from django.urls import path

urlpatterns = [
  path('like/<int:user_id>/', like)
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    # path('individualpost/<str:username>/', views.individual, name='individual'),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.delete, name='delete'),
]

templates/profiles/bio.html
{% extends 'base.html' %}

{% block content  %}

<div class="bio">
  <form action="" method='post'>
    {% csrf_token %}
    {{ bio_form.as_p }}
    <button type='submit'>更新</button>
  </form>
</div>

{% endblock content  %}

templates/profiles/profile.html
{% extends 'base.html' %}

{% block content %}

<div class="profile">
  
  {% if profile_user %}
    
    
  <h1 class='white'>{{ profile_user.username }}さんのプロフィール</h1>

  <p class='white'>{{ profile_user.bio }}</p>
  
  {% if user.is_authenticated and user == profile_user %}
    <a href="{% url 'accounts:bio' profile_user.username %}">編集</a>
  {% endif %}

  <div class="followBtn">
    <a class='followlist' href='{% url "followlist" profile_user.id %}'>フォロー:{{ followings.count }}</a>
    <a class='followerlist' href='{% url "followerlist" profile_user.id %}'>フォロワー:{{ followers.count }}</a>
  </div>

  <p class='white'>これまでの投稿数:{{ post_count }}件</p>

   <form action="{% url 'follow' profile_user.id %}" method='post'>
    {% csrf_token %}
    {% if is_following%}
    <button type='submit'>フォロー解除</button>
    {% else %}
    {% if user.is_authenticated and user != profile_user %} {# 自分をフォローできないように #}
    <button type='submit'>フォローする</button>
    {% endif %}
    {% endif %}
  </form> 

  <h2>ーーーーーーーーー投稿一覧ーーーーーーーーー</h2>
    {% for data in data_list %}
      <div class="postCard">
        <p>{{ data.created_at }}</p>
        <p class='content'>{{ data.content }}</p>
        <div class="buttons">
          <a class='update' href="{% url 'posts:update' data.pk %}">編集</a>
          <a class='delete' href="{% url 'posts:delete' data.id %}">削除</a>
        </div>
      </div>
      
    {% endfor %}
  
</div>
  {% endif %}

{% endblock %}